/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
 
    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Core colors from CSS variables
        current: 'currentColor',
        inherit: 'inherit',
        transparent: 'transparent',
        white: '#ffffff',
        black: '#000000',
        gray: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        // Custom theme colors using CSS variables
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        sidebarBg: 'var(--color-sidebar-bg)',
        sidebarBorder: 'var(--color-sidebar-border)',
        sidebarItemActiveBg: 'var(--color-sidebar-item-active-bg)',
        sidebarItemHoverBg: 'var(--color-sidebar-item-hover-bg)',
        sidebarItemText: 'var(--color-sidebar-item-text)',
        sidebarItemActiveText: 'var(--color-sidebar-item-active-text)',
        headerBg: 'var(--color-header-bg)',
        headerBorder: 'var(--color-header-border)',
        cardBg: 'var(--color-card-bg)',
        cardBorder: 'var(--color-card-border)',
        cardShadow: 'var(--color-card-shadow)',
        textPrimary: 'var(--color-text-primary)',
        textSecondary: 'var(--color-text-secondary)',
        textSubtle: 'var(--color-text-subtle)',
        textAccent: 'var(--color-text-accent)',
        inputBg: 'var(--color-input-bg)',
        inputBorder: 'var(--color-input-border)',
        inputPlaceholder: 'var(--color-input-placeholder)',
        inputFocusBorder: 'var(--color-input-focus-border)',
        inputFocusRing: 'var(--color-input-focus-ring)',
        buttonPrimaryBg: 'var(--color-button-primary-bg)',
        buttonPrimaryText: 'var(--color-button-primary-text)',
        buttonSecondaryBg: 'var(--color-button-secondary-bg)',
        buttonSecondaryText: 'var(--color-button-secondary-text)',
        buttonOutlineBorder: 'var(--color-button-outline-border)',
        buttonOutlineText: 'var(--color-button-outline-text)',
        badgeFeatureBg: 'var(--color-badge-feature-bg)',
        badgeFeatureText: 'var(--color-badge-feature-text)',
        badgeBugBg: 'var(--color-badge-bug-bg)',
        badgeBugText: 'var(--color-badge-bug-text)',
        badgeReviewBg: 'var(--color-badge-review-bg)',
        badgeReviewText: 'var(--color-badge-review-text)',
        badgeTestingBg: 'var(--color-badge-testing-bg)',
        badgeTestingText: 'var(--color-badge-testing-text)',
        priorityHighBg: 'var(--color-priority-high-bg)',
        priorityHighText: 'var(--color-priority-high-text)',
        priorityMediumBg: 'var(--color-priority-medium-bg)',
        priorityMediumText: 'var(--color-priority-medium-text)',
        priorityLowBg: 'var(--color-priority-low-bg)',
        priorityLowText: 'var(--color-priority-low-text)',
      },
      backgroundImage: {
        // No gradients for the dashboard design, keeping this empty for now.
      },
    },
  },
  plugins: [],
}
