-- WARNING: This schema is for context only and is not meant to be run.

-- Table order and constraints may not be valid for execution.

CREATE TABLE public.allowance_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  allowance_type USER-DEFINED NOT NULL,
  description text,
  calculation_method USER-DEFINED NOT NULL,
  default_amount numeric,
  default_percentage numeric,
  frequency USER-DEFINED NOT NULL DEFAULT 'per_pay_period'::allowance_frequency,
  is_taxable boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT allowance_configs_pkey PRIMARY KEY (id),
  CONSTRAINT allowance_configs_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.deduction_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  deduction_type USER-DEFINED NOT NULL,
  description text,
  calculation_method USER-DEFINED NOT NULL,
  fixed_amount numeric,
  percentage numeric,
  min_amount numeric,
  max_amount numeric,
  annual_max_amount numeric,
  employer_contribution_percentage numeric,
  employer_contribution_fixed numeric,
  is_mandatory boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deduction_configs_pkey PRIMARY KEY (id),
  CONSTRAINT deduction_configs_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  head_user_id uuid,
  budget_code text,
  cost_center_code text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id),
  CONSTRAINT fk_departments_head_user_id FOREIGN KEY (head_user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.employee_advances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  advance_number text NOT NULL UNIQUE,
  amount numeric NOT NULL,
  reason text NOT NULL,
  repayment_start_date date NOT NULL,
  repayment_amount_per_period numeric NOT NULL,
  total_repaid numeric NOT NULL DEFAULT 0.00,
  balance_remaining numeric NOT NULL,
  is_fully_repaid boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  paid_at timestamp with time zone,
  paid_by uuid,
  payment_reference text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_advances_pkey PRIMARY KEY (id),
  CONSTRAINT employee_advances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_advances_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id),
  CONSTRAINT employee_advances_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.employee_allowances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  allowance_config_id uuid NOT NULL,
  custom_amount numeric,
  custom_percentage numeric,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_allowances_pkey PRIMARY KEY (id),
  CONSTRAINT employee_allowances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_allowances_allowance_config_id_fkey FOREIGN KEY (allowance_config_id) REFERENCES public.allowance_configs(id)
);
CREATE TABLE public.employee_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  job_position_id uuid NOT NULL,
  department_id uuid NOT NULL,
  assignment_number text NOT NULL,
  pay_rate_type USER-DEFINED NOT NULL,
  hourly_rate numeric,
  salary_amount numeric,
  stipend_amount numeric,
  max_hours_per_week numeric,
  max_hours_per_pay_period numeric,
  start_date date NOT NULL,
  end_date date,
  is_approved boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT employee_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_assignments_job_position_id_fkey FOREIGN KEY (job_position_id) REFERENCES public.job_positions(id),
  CONSTRAINT employee_assignments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT employee_assignments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.employee_bank_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  bank_name text NOT NULL,
  account_holder_name text NOT NULL,
  account_number text NOT NULL,
  routing_number text NOT NULL,
  account_type text NOT NULL DEFAULT 'checking'::text,
  is_primary boolean NOT NULL DEFAULT false,
  is_verified boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_bank_accounts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_deductions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  deduction_config_id uuid NOT NULL,
  custom_amount numeric,
  custom_percentage numeric,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_deductions_pkey PRIMARY KEY (id),
  CONSTRAINT employee_deductions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_deductions_deduction_config_id_fkey FOREIGN KEY (deduction_config_id) REFERENCES public.deduction_configs(id)
);
CREATE TABLE public.employee_salary_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  previous_pay_rate_type USER-DEFINED,
  previous_hourly_rate numeric,
  previous_salary_amount numeric,
  new_pay_rate_type USER-DEFINED NOT NULL,
  new_hourly_rate numeric,
  new_salary_amount numeric,
  salary_grade_id uuid,
  change_type text NOT NULL,
  change_reason text,
  percentage_change numeric,
  effective_date date NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_salary_history_pkey PRIMARY KEY (id),
  CONSTRAINT employee_salary_history_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_salary_history_salary_grade_id_fkey FOREIGN KEY (salary_grade_id) REFERENCES public.salary_grades(id),
  CONSTRAINT employee_salary_history_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.employee_supervisors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  supervisor_user_id uuid NOT NULL,
  assignment_id uuid,
  can_approve_timesheets boolean NOT NULL DEFAULT true,
  can_adjust_pay boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_supervisors_pkey PRIMARY KEY (id),
  CONSTRAINT employee_supervisors_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_supervisors_supervisor_user_id_fkey FOREIGN KEY (supervisor_user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT employee_supervisors_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.employee_assignments(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  university_id uuid NOT NULL,
  department_id uuid,
  employee_number text NOT NULL,
  student_id text,
  employee_type USER-DEFINED NOT NULL,
  employment_status USER-DEFINED NOT NULL DEFAULT 'active'::employment_status,
  hire_date date NOT NULL,
  termination_date date,
  tax_id text,
  tax_withholding_rate numeric DEFAULT 0.00,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT employees_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id),
  CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.job_positions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  department_id uuid,
  title text NOT NULL,
  code text NOT NULL,
  description text,
  pay_rate_type USER-DEFINED NOT NULL,
  default_hourly_rate numeric,
  default_salary numeric,
  max_hours_per_week numeric,
  max_hours_per_pay_period numeric,
  requires_approval boolean NOT NULL DEFAULT false,
  min_gpa numeric,
  status USER-DEFINED NOT NULL DEFAULT 'active'::position_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_positions_pkey PRIMARY KEY (id),
  CONSTRAINT job_positions_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id),
  CONSTRAINT job_positions_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.payment_allowances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_payment_id uuid NOT NULL,
  allowance_config_id uuid NOT NULL,
  allowance_name text NOT NULL,
  allowance_type USER-DEFINED NOT NULL,
  calculation_method USER-DEFINED NOT NULL,
  percentage_applied numeric,
  base_amount numeric NOT NULL,
  allowance_amount numeric NOT NULL,
  is_taxable boolean NOT NULL,
  year_to_date_amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_allowances_pkey PRIMARY KEY (id),
  CONSTRAINT payment_allowances_payroll_payment_id_fkey FOREIGN KEY (payroll_payment_id) REFERENCES public.payroll_payments(id),
  CONSTRAINT payment_allowances_allowance_config_id_fkey FOREIGN KEY (allowance_config_id) REFERENCES public.allowance_configs(id)
);
CREATE TABLE public.payment_deductions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_payment_id uuid NOT NULL,
  deduction_config_id uuid NOT NULL,
  deduction_name text NOT NULL,
  deduction_type USER-DEFINED NOT NULL,
  calculation_method USER-DEFINED NOT NULL,
  percentage_applied numeric,
  gross_amount numeric NOT NULL,
  deduction_amount numeric NOT NULL,
  employer_contribution_amount numeric NOT NULL DEFAULT 0.00,
  employer_contribution_fixed numeric,
  year_to_date_amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_deductions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_deductions_payroll_payment_id_fkey FOREIGN KEY (payroll_payment_id) REFERENCES public.payroll_payments(id),
  CONSTRAINT payment_deductions_deduction_config_id_fkey FOREIGN KEY (deduction_config_id) REFERENCES public.deduction_configs(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_payment_id uuid NOT NULL,
  transaction_type text NOT NULL,
  amount numeric NOT NULL,
  bank_account_id uuid,
  payment_method text NOT NULL,
  transaction_reference text,
  processor_name text,
  processor_transaction_id text,
  processor_fee numeric,
  status USER-DEFINED NOT NULL,
  initiated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  notes text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_payroll_payment_id_fkey FOREIGN KEY (payroll_payment_id) REFERENCES public.payroll_payments(id),
  CONSTRAINT payment_transactions_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.employee_bank_accounts(id)
);
CREATE TABLE public.payroll_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_run_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  assignment_id uuid NOT NULL,
  timesheet_id uuid,
  regular_hours numeric NOT NULL DEFAULT 0.00,
  overtime_hours numeric NOT NULL DEFAULT 0.00,
  hourly_rate numeric,
  gross_pay numeric NOT NULL,
  total_deductions numeric NOT NULL DEFAULT 0.00,
  net_pay numeric NOT NULL,
  payment_method text NOT NULL DEFAULT 'direct_deposit'::text,
  bank_account_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  paid_at timestamp with time zone,
  transaction_reference text,
  notes text,
  calculation_details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_payments_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_payments_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id),
  CONSTRAINT payroll_payments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payroll_payments_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.employee_assignments(id),
  CONSTRAINT payroll_payments_timesheet_id_fkey FOREIGN KEY (timesheet_id) REFERENCES public.timesheets(id),
  CONSTRAINT payroll_payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.employee_bank_accounts(id)
);
CREATE TABLE public.payroll_periods (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  period_name text NOT NULL,
  period_start_date date NOT NULL,
  period_end_date date NOT NULL,
  payment_date date NOT NULL,
  frequency USER-DEFINED NOT NULL,
  is_closed boolean NOT NULL DEFAULT false,
  closed_at timestamp with time zone,
  closed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_periods_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_periods_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id),
  CONSTRAINT payroll_periods_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.payroll_runs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  payroll_period_id uuid NOT NULL,
  run_number text NOT NULL UNIQUE,
  run_name text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::payroll_run_status,
  total_employees integer NOT NULL DEFAULT 0,
  total_gross_pay numeric NOT NULL DEFAULT 0.00,
  total_deductions numeric NOT NULL DEFAULT 0.00,
  total_net_pay numeric NOT NULL DEFAULT 0.00,
  total_employer_costs numeric NOT NULL DEFAULT 0.00,
  calculated_at timestamp with time zone,
  calculated_by uuid,
  approved_at timestamp with time zone,
  approved_by uuid,
  approval_notes text,
  processed_at timestamp with time zone,
  processed_by uuid,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_runs_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id),
  CONSTRAINT payroll_runs_payroll_period_id_fkey FOREIGN KEY (payroll_period_id) REFERENCES public.payroll_periods(id),
  CONSTRAINT payroll_runs_calculated_by_fkey FOREIGN KEY (calculated_by) REFERENCES public.user_profiles(id),
  CONSTRAINT payroll_runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id),
  CONSTRAINT payroll_runs_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.salary_grades (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  university_id uuid NOT NULL,
  grade_name text NOT NULL,
  grade_level integer NOT NULL,
  description text,
  min_salary numeric NOT NULL,
  mid_salary numeric NOT NULL,
  max_salary numeric NOT NULL,
  min_hourly_rate numeric,
  max_hourly_rate numeric,
  currency text NOT NULL DEFAULT 'USD'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_grades_pkey PRIMARY KEY (id),
  CONSTRAINT salary_grades_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id)
);
CREATE TABLE public.time_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  timesheet_id uuid NOT NULL,
  work_date date NOT NULL,
  entry_type USER-DEFINED NOT NULL DEFAULT 'regular'::time_entry_type,
  clock_in_time timestamp with time zone,
  clock_out_time timestamp with time zone,
  break_duration_minutes integer DEFAULT 0,
  hours_worked numeric NOT NULL,
  description text,
  location text,
  is_verified boolean NOT NULL DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_entries_pkey PRIMARY KEY (id),
  CONSTRAINT time_entries_timesheet_id_fkey FOREIGN KEY (timesheet_id) REFERENCES public.timesheets(id),
  CONSTRAINT time_entries_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.time_entry_adjustments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  time_entry_id uuid NOT NULL,
  original_hours numeric NOT NULL,
  original_entry_type USER-DEFINED NOT NULL,
  adjusted_hours numeric NOT NULL,
  adjusted_entry_type USER-DEFINED NOT NULL,
  adjustment_reason text NOT NULL,
  adjusted_by uuid NOT NULL,
  adjusted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_entry_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT time_entry_adjustments_time_entry_id_fkey FOREIGN KEY (time_entry_id) REFERENCES public.time_entries(id),
  CONSTRAINT time_entry_adjustments_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.timesheets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  assignment_id uuid NOT NULL,
  period_start_date date NOT NULL,
  period_end_date date NOT NULL,
  total_regular_hours numeric NOT NULL DEFAULT 0.00,
  total_overtime_hours numeric NOT NULL DEFAULT 0.00,
  total_hours numeric NOT NULL DEFAULT 0.00,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::timesheet_status,
  submitted_at timestamp with time zone,
  submitted_by uuid,
  approved_at timestamp with time zone,
  approved_by uuid,
  approval_notes text,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  processed_at timestamp with time zone,
  processed_by uuid,
  employee_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT timesheets_pkey PRIMARY KEY (id),
  CONSTRAINT timesheets_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT timesheets_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.employee_assignments(id),
  CONSTRAINT timesheets_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.user_profiles(id),
  CONSTRAINT timesheets_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id),
  CONSTRAINT timesheets_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.user_profiles(id),
  CONSTRAINT timesheets_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.universities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  short_name text NOT NULL UNIQUE,
  type USER-DEFINED NOT NULL DEFAULT 'university'::institution_type,
  status USER-DEFINED NOT NULL DEFAULT 'active'::institution_status,
  email text NOT NULL,
  phone text,
  website text,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state_province text NOT NULL,
  country text NOT NULL,
  postal_code text NOT NULL,
  tax_id text,
  registration_number text,
  default_currency text NOT NULL DEFAULT 'USD'::text,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  fiscal_year_start_month integer DEFAULT 1 CHECK (fiscal_year_start_month >= 1 AND fiscal_year_start_month <= 12),
  logo_url text,
  primary_color text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT universities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  university_id uuid,
  email text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  phone_number text,
  date_of_birth date,
  address_line1 text,
  address_line2 text,
  city text,
  state_province text,
  country text,
  postal_code text,
  role USER-DEFINED NOT NULL DEFAULT 'employee'::user_role,
  profile_image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  username text UNIQUE,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(id)
);
